-- MEIO ADMISSÃO
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Ata de organização');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Batismo infantil');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Profissão de fé');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Batismo e profissão de fé');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Transferência');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Transferência dos responsáveis');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Restauração');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Jurisdição ex-officio');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Jurisdição a pedido');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Jurisdição assumida sobre os responsáveis');
INSERT INTO ips.corporativo.meio_admissao values (nextval('corporativo.sq_meio_admissao'), 'Designação do presbitério');

-- CARGO
INSERT INTO ips.corporativo.cargo values (nextval('corporativo.sq_cargo'), 'Ministério de comunicação');
INSERT INTO ips.corporativo.cargo values (nextval('corporativo.sq_cargo'), 'Ministério de integração');
INSERT INTO ips.corporativo.cargo values (nextval('corporativo.sq_cargo'), 'Ministério de música');
INSERT INTO ips.corporativo.cargo values (nextval('corporativo.sq_cargo'), 'Missões');

-- PROCEDÊNCIA
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Catolicismo Romano');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Esoterismo/Orientalismo');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Espiritismo afrobrasileiro');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Espiritismo kardecista');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Fundador da 1 ª IPS');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Igreja evangélica');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Igreja Presbiteriana do Brasil');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Igreja Presb. Independente');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Islamismo');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Adventismo');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Testemunhas de Jeová');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Mormonismo');
INSERT INTO ips.corporativo.procedencia values (nextval('corporativo.sq_procedencia'), 'Nenhuma igreja');

-- PROFISSÃO
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador de Rede');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador(a) de Banco de Dados');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador(a) de Empresas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador(a) de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administrador(a) Hospitalar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Administradora de Serviços do Lar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Advogado(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Agente Ambiental');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Agricultor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Agrônomo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Agropecuarista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ajudante de Caminhão');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ajudante de Composição');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ajudante de Foguista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ajudante de Vidreiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Almoxarife');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Administrativo (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Contábil');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Administração de Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Captação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Contratos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Controladoria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Controle Interno');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Crédito');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Custos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Departamento Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Exportação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Faturamento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de IT');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Laboratório');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Logística');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Marketing');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Negócios');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Orçamentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Organização e Métodos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Remuneração Senior');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Sistemas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Suporte Administrativo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Suporte Pleno');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Tecidos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista de Vendas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Fiscal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Senior de Previdência Privada');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Analista Tributária');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Apicultor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Aposentado(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Armador de Pesca');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Arquiteto(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Artesão(ã)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Administrativo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Comercial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Contábil');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Contas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Departamento Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Escritório');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Faturamento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Gerencia de R.H.');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Hotelaria Hospitalar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Planejamento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Processo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Produção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente de Suprimentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Jurídico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Social');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Assistente Técnico Operacional');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Atendente');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ator');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Atriz');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auditor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auditor(a) Fiscal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Autônomo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Aux. de Serviços Gerais');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Acadêmico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Administrativo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Contábil');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Compras');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Cozinha');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Departamento de Crédito');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Departamento Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Departamento Fiscal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de eletricista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Enfermagem');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Escritório');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Inspeção de Qualidade');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Laboratório');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de RH');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar de Serviços');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Operacional');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Auxiliar Técnico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Avicultor( a )');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Bailarina (o)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Bancário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Biólogo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Biomédico (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Cabeleireiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Caminhoneiro (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'carregador');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Catador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Catraqueiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Chefe da Secretaria de Expediente');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Chefe de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Chefe de Serviços de Transporte');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Cirurgião(ã) Dentista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Citricultor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coletor(a) de Material Reciclável');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Comerciante');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Comerciário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Comprador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Comunicador(a) Social');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Condutor(a) Autônomo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Condutor(a) Escolar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Conferente');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'construtor');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Consultor(a) Administrativo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Consultor(a) de Vendas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Contabilista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Contador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Contramestre');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Controller');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) Administrativo Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Atendimento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Controladoria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Controle de Qualidade');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Controle Interno');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Engenharia Industrial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Exportação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Impostos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Instrumentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Manutenção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Produção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Projetos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Suprimentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Transportes');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) de Vendas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coordenador(a) Pedagógico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Coreógrafo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Corretor(a) de Imóveis');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Corretor(a) de Seguros');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Costureiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Cozinheiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Cronoanalista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Cuidador(a) de idoso');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Dançarina');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Delegado');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Dentista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Desenvolvedor de Arte');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Desenvolvedor de Produtos Texteis');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Despachante');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Digitador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor (a) Executivo (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor de Escola');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor(a) de Assuntos Técnicos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor(a) de Criação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor(a) de Produções');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor(a) de Relações Públicas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Diretor(a) de Relações Públicas e Sociais');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Do lar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Economista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Eletricista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Eletricitário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Embalador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Embalador(a) de Produtos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Empregada Doméstica');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Empresário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Empresário(a) Rural');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Encarregado Automotivo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Encarregado de Controladoria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Encarregado(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Encarregado(a) de Mídia');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Enfermeiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Administrador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) de Alimentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) de Desenvolvimento Ambiental');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) de Segurança do Trabalho');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Eletricista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Florestal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Mecânico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Naval');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Engenheiro(a) Químico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Escrevente Técnico Judiciário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Escrituraria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Escriturario(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Especialista em Banco de Dados');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Estudante');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Farmacêutica(o)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Faturista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'faxineira (o)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ferramenteiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ferroviário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Fisioterapeuta');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Floricultor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Fotógrafo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Funcionário(a) Público(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'funileiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Geógrafo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Geólogo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Área');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Contabilidade');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Crédito e Cobrança');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Faturamento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Serviços de Transporte');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Sistemas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Tecnologa da Informação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Tributário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Vendas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente de Vendas Distribuidores');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente Departamento de Compra');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente Operacional');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gerente Regional de Vendas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gestor(a) de Logística');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gestor(a) de Negócios');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gestor(a) de Projetos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Gestor(a) Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Impressor');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Industriário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Inspetor de Qualidade');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Instrumentista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Intérprete');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Jardineiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Jornalista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Lavrador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Líder de Embalagem');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Líder de Higienização');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Líder de Recepção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Marceneiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Matemático(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Mecânico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Mecânico de Manutenção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Medico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Médico(a) Pediátrico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Médico(a) Veterinário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Metalúrgico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Militar');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Ministro Religioso');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Motorista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Nutricionista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Odontólogo (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Oficial de Cartório');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Oficial de Justiça');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Oficial de Promotoria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Oleiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador (a) de Crédito Rural');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador de Caldeira');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador de Conicaleira');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador de Máquina');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador de Texturização');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador(a) de Caldeira');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador(a) de Forming');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador(a) de Imagem');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Operador(a) de Máquinas');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Orientador(a) Educacional');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Pecuarista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Pedagogo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'pedreiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Pedreiro Refratarista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Planejador(a) de Manutenção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Policial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Policial Rodoviário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Porteiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Produtor(a) Agropecuário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Produtor(a) Rural');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Professor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Profissional Liberal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Programador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Psicólogo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Publicitário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Químico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Reciclador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Reciclador(a) Ambiental Autônomo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Recobridor');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Representante Comercial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Secretária Bilíngue');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Secretária de Diretoria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Secretária Executiva');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Secretária(o)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Securitário(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Segurança');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Selecionador(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Serralherio');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Servidor(a) Público(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Sociólogo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) Administrativo');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Adminstração de Pessoal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Atendimento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Compras');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Custos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Elétrica e Instrumentação');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Manufatura');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Manutenção Industrial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Matéria-Prima');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Operações');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Produção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Suprimentos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) de Tesouraria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) Financeiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Supervisor(a) Fiscal');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tabelião');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Taxista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecelão');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técinico em Kaizen');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnica Agropecuária');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico (a) Administrativo (a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico (a) em Recursos Humanos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico Agropecuário');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico de Métodos Gráficos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico de Operação de Usina Hidrelétrica');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico de Tinturaria');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico em Informática');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico em Processamento');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) Agrícola');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) de Enfermagem');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) de Gesso');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) de Manutenção Elétrico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) de Processos');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Contabilidade');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Edificações');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Eletrônica');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Informática');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Meio Ambiente');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Plástico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Radiologia Médica');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) em Segurança do Trabalho');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) Mecânico(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Técnico(a) Químico Industrial');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo do Produto Sênior');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo em Gestão Financeira');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo em Telecomunicações');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo(a) de Processo de Produção');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo(a) em Processamento de Dados');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tecnólogo(a) Mecânico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Telefonista');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tintureiro');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Torneiro Mecânico');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Tradutor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Urdidor');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Vendedor(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Vidreiro(a)');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Vigilante');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Web Designer');
INSERT INTO ips.corporativo.profissao values (nextval('corporativo.sq_profissao'), 'Zootécnico(a)');